#include "bestiary.h"
void rat() {
	system("cls");
	int i = 65;
	gotoxy(i, 3);
	printf_s("         -@##:");
	gotoxy(i, 4);
	printf_s("         #+  :###====@#+");
	gotoxy(i, 5);
	printf_s("         .@#:     -. ..##.");
	gotoxy(i, 6);
	printf_s("           *#.   -#- @@ :#:");
	gotoxy(i, 7);
	printf_s("          -#+            ##");
	gotoxy(i, 8);
	printf_s("         :#:       :#===@##.");
	gotoxy(i, 9);
	printf_s("        -#*    .::.@=#@*-+*.");
	gotoxy(i, 10);
	printf_s("        @=      .:#-+##*");
	gotoxy(i, 11);
	printf_s("        @+        #* #=#+");
	gotoxy(i, 12);
	printf_s("        @+             +#");
	gotoxy(i, 13);
	printf_s("        #+             +#");
	gotoxy(i, 14);
	printf_s("  *#########@======###@#=");
}
void goblin() {
	system("cls");
	int i = 65;
	gotoxy(i, 3);
	printf_s("    ^          ^");
	gotoxy(i, 4);
	printf_s("   / \\        / \\");
	gotoxy(i, 5);
	printf_s(" /*   *------*   *\\");
	gotoxy(i, 6);
	printf_s("|  (@)        (@)  |");
	gotoxy(i, 7);
	printf_s(" \\       /        /");
	gotoxy(i, 8);
	printf_s("  \\              /");
	gotoxy(i, 9);
	printf_s("   \\___  ~~  ___/");
	gotoxy(i, 10);
	printf_s("       \\____/");
}
void bandit() {
	system("cls");
	int i = 65;
	gotoxy(i, 3);
	printf_s("   _______________");
	gotoxy(i, 4);
	printf_s("  / ---       --- \\");
	gotoxy(i, 5);
	printf_s(" |  /-/       /-/  |");
	gotoxy(i, 6);
	printf_s("(|        /        |)");
	gotoxy(i, 7);
	printf_s(" |        '        |           ______");
	gotoxy(i, 8);
	printf_s("  \\               /           \\    |");
	gotoxy(i, 9);
	printf_s("   \\__  ___    __/  /||||______\\   |");
	gotoxy(i, 10);
	printf_s("      \\_______/    /  _/-----------|");
	gotoxy(i, 11);
	printf_s("       _/   \\_    /  /");
	gotoxy(i, 12);
	printf_s("      /       \\__/  /");
}
void skeleton() {
	system("cls");
	int i = 65;
	gotoxy(i, 3);
	printf_s("         -@##:");
	gotoxy(i, 4);
	printf_s("   .=#=*:");
	gotoxy(i, 5);
	printf_s("  =#######:");
	gotoxy(i, 6);
	printf_s(" ## ### ##");
	gotoxy(i, 7);
	printf_s(" *########*");
	gotoxy(i, 8);
	printf_s("   # # #.");
	gotoxy(i, 9);
	printf_s(" ....##....");
	gotoxy(i, 10);
	printf_s("--:**##+**-:");
	gotoxy(i, 11);
	printf_s("=* :*##=* *=");
	gotoxy(i, 12);
	printf_s("#+ +###@#.*@");
	gotoxy(i, 13);
	printf_s("     *=");
	gotoxy(i, 14);
	printf_s("    #:-#.");
	gotoxy(i, 15);
	printf_s("    #--@");
	gotoxy(i, 16);
	printf_s("   .#:-#");
}