#include "struct.h"
void room0();
void room1();
void room2();
void room3();
void room4();
void room5();
void room6();
void shop();
void intro();
void picture();
int stage0();
int stage1();
int stage2();
int stage3();
int stage4();
void stages();