#include "rules.h"
void room0();
void room1();
void room2();
void room3();
void room4();
void room5();
void room6();
void room7();
void room8();
void room9();
void shop();
void picture();
int stage0();
int stage2();
int stage3();
int stage4();
int stage5();
void stages();