#include "struct.h"
void rulerat();
void rulebandit();
void rulegoblin();
void ruleskeleton();
void rulesword();
void ruleset();
void modif();
void money();
void loot();
int roll(int amount,int dice,int mods);
void levels();
void warlock2();
void proficiency();
void condition(int* attack);
void weapons(int z, int* damage, int* attack, char* damagetype);
int abilitydesc(int z, int* damage, int* characteristic);
int spell(int*attack,int z, int* damage, char* typeofdamage);
void shortrest();
int amountofspells();
void profinskills();
void equips(int id);
void showequip();
void skills();
void characterlist();